
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puzwsgpnqkbbntlxmgjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1endzZ3BucWtiYm50bHhtZ2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODU1NTksImV4cCI6MjA2MTY2MTU1OX0.S-Kd1iHzSQ8X8nBtlVfBMnXKxojq7dKy3ViiMb9BHwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
